name: usvprocessing
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=h1c43f85_4
  - brotli-bin=1.1.0=h1c43f85_4
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hedd4973_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py312h2ac44ba_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - freetype=2.14.1=h694c41f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.9=py312hef387a8_1
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libblas=3.9.0=34_h7f60823_openblas
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.9.0=34_hff6cab4_openblas
  - libcxx=20.1.8=h3d58e20_1
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgfortran=15.1.0=h5f6db21_0
  - libgfortran5=15.1.0=hfa3c126_0
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=34_h236ab99_openblas
  - liblzma=5.8.1=hd471939_2
  - liblzma-devel=5.8.1=hd471939_2
  - libopenblas=0.3.30=openmp_h83c2472_1
  - libpng=1.6.50=h84aeda2_1
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.50.4=h39a8b3b_0
  - libtiff=4.7.1=haa3b502_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=20.1.8=hf4e0ed4_1
  - matplotlib=3.10.7=py312hb401068_0
  - matplotlib-base=3.10.7=py312h7894933_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.5.4=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py312hec45ffd_3
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h051e184_3
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h01d7ebd_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.1=h9f0c242_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.0.1=py312hbb7883b_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312h391ab28_1
  - tk=8.6.13=hf689a15_2
  - tornado=6.5.2=py312h2f459f6_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h2f459f6_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xz=5.8.1=h357f2ed_2
  - xz-gpl-tools=5.8.1=h357f2ed_2
  - xz-tools=5.8.1=hd471939_2
  - zeromq=4.3.5=h7130eaa_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h8210216_2
  - pip:
      - audioread==3.0.1
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - fonttools==4.59.0
      - idna==3.10
      - ipykernel==7.0.1
      - joblib==1.5.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - msgpack==1.1.1
      - numba==0.61.2
      - numpy==2.2.6
      - pooch==1.8.2
      - pycparser==2.22
      - pyparsing==3.2.3
      - requests==2.32.4
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - threadpoolctl==3.6.0
      - urllib3==2.5.0
prefix: /Users/sophieneale/miniforge3/envs/usvprocessing
