name: usvprocessing
channels:
  - conda-forge
dependencies:
  - python=3.12.1
  - ipykernel
  - pip
  - numpy==2.2.0
  - pandas==2.2.3
  - seaborn
  - matplotlib
  - statsmodels
  - chardet
prefix: /Users/sophieneale/miniforge3/envs/usvprocessing
